// Generated by gencpp from file my_city/GPSLocation.msg
// DO NOT EDIT!


#ifndef MY_CITY_MESSAGE_GPSLOCATION_H
#define MY_CITY_MESSAGE_GPSLOCATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_city
{
template <class ContainerAllocator>
struct GPSLocation_
{
  typedef GPSLocation_<ContainerAllocator> Type;

  GPSLocation_()
    : latitude(0.0)
    , longitude(0.0)  {
    }
  GPSLocation_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;





  typedef boost::shared_ptr< ::my_city::GPSLocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_city::GPSLocation_<ContainerAllocator> const> ConstPtr;

}; // struct GPSLocation_

typedef ::my_city::GPSLocation_<std::allocator<void> > GPSLocation;

typedef boost::shared_ptr< ::my_city::GPSLocation > GPSLocationPtr;
typedef boost::shared_ptr< ::my_city::GPSLocation const> GPSLocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_city::GPSLocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_city::GPSLocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_city::GPSLocation_<ContainerAllocator1> & lhs, const ::my_city::GPSLocation_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_city::GPSLocation_<ContainerAllocator1> & lhs, const ::my_city::GPSLocation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_city

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_city::GPSLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_city::GPSLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_city::GPSLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_city::GPSLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_city::GPSLocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_city::GPSLocation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_city::GPSLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "680c6dc7da65a2421a822205dcbdb600";
  }

  static const char* value(const ::my_city::GPSLocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x680c6dc7da65a242ULL;
  static const uint64_t static_value2 = 0x1a822205dcbdb600ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_city::GPSLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_city/GPSLocation";
  }

  static const char* value(const ::my_city::GPSLocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_city::GPSLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
;
  }

  static const char* value(const ::my_city::GPSLocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_city::GPSLocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPSLocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_city::GPSLocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_city::GPSLocation_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CITY_MESSAGE_GPSLOCATION_H
