// Generated by gencpp from file my_city/WeatherService.msg
// DO NOT EDIT!


#ifndef MY_CITY_MESSAGE_WEATHERSERVICE_H
#define MY_CITY_MESSAGE_WEATHERSERVICE_H

#include <ros/service_traits.h>


#include <my_city/WeatherServiceRequest.h>
#include <my_city/WeatherServiceResponse.h>


namespace my_city
{

struct WeatherService
{

typedef WeatherServiceRequest Request;
typedef WeatherServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WeatherService
} // namespace my_city


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_city::WeatherService > {
  static const char* value()
  {
    return "ec5c854fe33b5ba3e765055cce88be4e";
  }

  static const char* value(const ::my_city::WeatherService&) { return value(); }
};

template<>
struct DataType< ::my_city::WeatherService > {
  static const char* value()
  {
    return "my_city/WeatherService";
  }

  static const char* value(const ::my_city::WeatherService&) { return value(); }
};


// service_traits::MD5Sum< ::my_city::WeatherServiceRequest> should match
// service_traits::MD5Sum< ::my_city::WeatherService >
template<>
struct MD5Sum< ::my_city::WeatherServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_city::WeatherService >::value();
  }
  static const char* value(const ::my_city::WeatherServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_city::WeatherServiceRequest> should match
// service_traits::DataType< ::my_city::WeatherService >
template<>
struct DataType< ::my_city::WeatherServiceRequest>
{
  static const char* value()
  {
    return DataType< ::my_city::WeatherService >::value();
  }
  static const char* value(const ::my_city::WeatherServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_city::WeatherServiceResponse> should match
// service_traits::MD5Sum< ::my_city::WeatherService >
template<>
struct MD5Sum< ::my_city::WeatherServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_city::WeatherService >::value();
  }
  static const char* value(const ::my_city::WeatherServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_city::WeatherServiceResponse> should match
// service_traits::DataType< ::my_city::WeatherService >
template<>
struct DataType< ::my_city::WeatherServiceResponse>
{
  static const char* value()
  {
    return DataType< ::my_city::WeatherService >::value();
  }
  static const char* value(const ::my_city::WeatherServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_CITY_MESSAGE_WEATHERSERVICE_H
