// Generated by gencpp from file Homework4/OddEvenCheck.msg
// DO NOT EDIT!


#ifndef HOMEWORK4_MESSAGE_ODDEVENCHECK_H
#define HOMEWORK4_MESSAGE_ODDEVENCHECK_H

#include <ros/service_traits.h>


#include <Homework4/OddEvenCheckRequest.h>
#include <Homework4/OddEvenCheckResponse.h>


namespace Homework4
{

struct OddEvenCheck
{

typedef OddEvenCheckRequest Request;
typedef OddEvenCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OddEvenCheck
} // namespace Homework4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Homework4::OddEvenCheck > {
  static const char* value()
  {
    return "4ff0b0ab1ed04611e3a2b4090af9ee4f";
  }

  static const char* value(const ::Homework4::OddEvenCheck&) { return value(); }
};

template<>
struct DataType< ::Homework4::OddEvenCheck > {
  static const char* value()
  {
    return "Homework4/OddEvenCheck";
  }

  static const char* value(const ::Homework4::OddEvenCheck&) { return value(); }
};


// service_traits::MD5Sum< ::Homework4::OddEvenCheckRequest> should match
// service_traits::MD5Sum< ::Homework4::OddEvenCheck >
template<>
struct MD5Sum< ::Homework4::OddEvenCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Homework4::OddEvenCheck >::value();
  }
  static const char* value(const ::Homework4::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Homework4::OddEvenCheckRequest> should match
// service_traits::DataType< ::Homework4::OddEvenCheck >
template<>
struct DataType< ::Homework4::OddEvenCheckRequest>
{
  static const char* value()
  {
    return DataType< ::Homework4::OddEvenCheck >::value();
  }
  static const char* value(const ::Homework4::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Homework4::OddEvenCheckResponse> should match
// service_traits::MD5Sum< ::Homework4::OddEvenCheck >
template<>
struct MD5Sum< ::Homework4::OddEvenCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Homework4::OddEvenCheck >::value();
  }
  static const char* value(const ::Homework4::OddEvenCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Homework4::OddEvenCheckResponse> should match
// service_traits::DataType< ::Homework4::OddEvenCheck >
template<>
struct DataType< ::Homework4::OddEvenCheckResponse>
{
  static const char* value()
  {
    return DataType< ::Homework4::OddEvenCheck >::value();
  }
  static const char* value(const ::Homework4::OddEvenCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOMEWORK4_MESSAGE_ODDEVENCHECK_H
