// Auto-generated. Do not edit!

// (in-package project7.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FollowPathFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.total_distance_to_path = null;
    }
    else {
      if (initObj.hasOwnProperty('total_distance_to_path')) {
        this.total_distance_to_path = initObj.total_distance_to_path
      }
      else {
        this.total_distance_to_path = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FollowPathFeedback
    // Serialize message field [total_distance_to_path]
    bufferOffset = _serializer.float32(obj.total_distance_to_path, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FollowPathFeedback
    let len;
    let data = new FollowPathFeedback(null);
    // Deserialize message field [total_distance_to_path]
    data.total_distance_to_path = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'project7/FollowPathFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b37f6cb87e68ecced22623b0253fda11';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    float32 total_distance_to_path
    
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FollowPathFeedback(null);
    if (msg.total_distance_to_path !== undefined) {
      resolved.total_distance_to_path = msg.total_distance_to_path;
    }
    else {
      resolved.total_distance_to_path = 0.0
    }

    return resolved;
    }
};

module.exports = FollowPathFeedback;
