// Generated by gencpp from file project7/FollowPathFeedback.msg
// DO NOT EDIT!


#ifndef PROJECT7_MESSAGE_FOLLOWPATHFEEDBACK_H
#define PROJECT7_MESSAGE_FOLLOWPATHFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project7
{
template <class ContainerAllocator>
struct FollowPathFeedback_
{
  typedef FollowPathFeedback_<ContainerAllocator> Type;

  FollowPathFeedback_()
    : total_distance_to_path(0.0)  {
    }
  FollowPathFeedback_(const ContainerAllocator& _alloc)
    : total_distance_to_path(0.0)  {
  (void)_alloc;
    }



   typedef float _total_distance_to_path_type;
  _total_distance_to_path_type total_distance_to_path;





  typedef boost::shared_ptr< ::project7::FollowPathFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project7::FollowPathFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct FollowPathFeedback_

typedef ::project7::FollowPathFeedback_<std::allocator<void> > FollowPathFeedback;

typedef boost::shared_ptr< ::project7::FollowPathFeedback > FollowPathFeedbackPtr;
typedef boost::shared_ptr< ::project7::FollowPathFeedback const> FollowPathFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project7::FollowPathFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project7::FollowPathFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::project7::FollowPathFeedback_<ContainerAllocator1> & lhs, const ::project7::FollowPathFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.total_distance_to_path == rhs.total_distance_to_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::project7::FollowPathFeedback_<ContainerAllocator1> & lhs, const ::project7::FollowPathFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace project7

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::project7::FollowPathFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project7::FollowPathFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project7::FollowPathFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project7::FollowPathFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project7::FollowPathFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project7::FollowPathFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project7::FollowPathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b37f6cb87e68ecced22623b0253fda11";
  }

  static const char* value(const ::project7::FollowPathFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb37f6cb87e68ecceULL;
  static const uint64_t static_value2 = 0xd22623b0253fda11ULL;
};

template<class ContainerAllocator>
struct DataType< ::project7::FollowPathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project7/FollowPathFeedback";
  }

  static const char* value(const ::project7::FollowPathFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project7::FollowPathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float32 total_distance_to_path\n"
"\n"
"\n"
;
  }

  static const char* value(const ::project7::FollowPathFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project7::FollowPathFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_distance_to_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowPathFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project7::FollowPathFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project7::FollowPathFeedback_<ContainerAllocator>& v)
  {
    s << indent << "total_distance_to_path: ";
    Printer<float>::stream(s, indent + "  ", v.total_distance_to_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT7_MESSAGE_FOLLOWPATHFEEDBACK_H
