// Generated by gencpp from file weather_info/WeatherRequest.msg
// DO NOT EDIT!


#ifndef WEATHER_INFO_MESSAGE_WEATHERREQUEST_H
#define WEATHER_INFO_MESSAGE_WEATHERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace weather_info
{
template <class ContainerAllocator>
struct WeatherRequest_
{
  typedef WeatherRequest_<ContainerAllocator> Type;

  WeatherRequest_()
    : city()  {
    }
  WeatherRequest_(const ContainerAllocator& _alloc)
    : city(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _city_type;
  _city_type city;





  typedef boost::shared_ptr< ::weather_info::WeatherRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::weather_info::WeatherRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WeatherRequest_

typedef ::weather_info::WeatherRequest_<std::allocator<void> > WeatherRequest;

typedef boost::shared_ptr< ::weather_info::WeatherRequest > WeatherRequestPtr;
typedef boost::shared_ptr< ::weather_info::WeatherRequest const> WeatherRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::weather_info::WeatherRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::weather_info::WeatherRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::weather_info::WeatherRequest_<ContainerAllocator1> & lhs, const ::weather_info::WeatherRequest_<ContainerAllocator2> & rhs)
{
  return lhs.city == rhs.city;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::weather_info::WeatherRequest_<ContainerAllocator1> & lhs, const ::weather_info::WeatherRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace weather_info

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::weather_info::WeatherRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::weather_info::WeatherRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::weather_info::WeatherRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::weather_info::WeatherRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weather_info::WeatherRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weather_info::WeatherRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::weather_info::WeatherRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ca7c9808e023a3417491b7104889ca1";
  }

  static const char* value(const ::weather_info::WeatherRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ca7c9808e023a34ULL;
  static const uint64_t static_value2 = 0x17491b7104889ca1ULL;
};

template<class ContainerAllocator>
struct DataType< ::weather_info::WeatherRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "weather_info/WeatherRequest";
  }

  static const char* value(const ::weather_info::WeatherRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::weather_info::WeatherRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string city\n"
;
  }

  static const char* value(const ::weather_info::WeatherRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::weather_info::WeatherRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.city);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WeatherRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::weather_info::WeatherRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::weather_info::WeatherRequest_<ContainerAllocator>& v)
  {
    s << indent << "city: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.city);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEATHER_INFO_MESSAGE_WEATHERREQUEST_H
