// Generated by gencpp from file weather_info/WeatherResponse.msg
// DO NOT EDIT!


#ifndef WEATHER_INFO_MESSAGE_WEATHERRESPONSE_H
#define WEATHER_INFO_MESSAGE_WEATHERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace weather_info
{
template <class ContainerAllocator>
struct WeatherResponse_
{
  typedef WeatherResponse_<ContainerAllocator> Type;

  WeatherResponse_()
    : city_name()
    , temperature(0.0)
    , humidity(0.0)
    , description()  {
    }
  WeatherResponse_(const ContainerAllocator& _alloc)
    : city_name(_alloc)
    , temperature(0.0)
    , humidity(0.0)
    , description(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _city_name_type;
  _city_name_type city_name;

   typedef float _temperature_type;
  _temperature_type temperature;

   typedef float _humidity_type;
  _humidity_type humidity;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _description_type;
  _description_type description;





  typedef boost::shared_ptr< ::weather_info::WeatherResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::weather_info::WeatherResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WeatherResponse_

typedef ::weather_info::WeatherResponse_<std::allocator<void> > WeatherResponse;

typedef boost::shared_ptr< ::weather_info::WeatherResponse > WeatherResponsePtr;
typedef boost::shared_ptr< ::weather_info::WeatherResponse const> WeatherResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::weather_info::WeatherResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::weather_info::WeatherResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::weather_info::WeatherResponse_<ContainerAllocator1> & lhs, const ::weather_info::WeatherResponse_<ContainerAllocator2> & rhs)
{
  return lhs.city_name == rhs.city_name &&
    lhs.temperature == rhs.temperature &&
    lhs.humidity == rhs.humidity &&
    lhs.description == rhs.description;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::weather_info::WeatherResponse_<ContainerAllocator1> & lhs, const ::weather_info::WeatherResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace weather_info

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::weather_info::WeatherResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::weather_info::WeatherResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::weather_info::WeatherResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::weather_info::WeatherResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weather_info::WeatherResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weather_info::WeatherResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::weather_info::WeatherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "182114dcdb307da4818df3386abb39b9";
  }

  static const char* value(const ::weather_info::WeatherResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x182114dcdb307da4ULL;
  static const uint64_t static_value2 = 0x818df3386abb39b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::weather_info::WeatherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "weather_info/WeatherResponse";
  }

  static const char* value(const ::weather_info::WeatherResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::weather_info::WeatherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string city_name\n"
"float32 temperature\n"
"float32 humidity\n"
"string description\n"
"\n"
"\n"
;
  }

  static const char* value(const ::weather_info::WeatherResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::weather_info::WeatherResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.city_name);
      stream.next(m.temperature);
      stream.next(m.humidity);
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WeatherResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::weather_info::WeatherResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::weather_info::WeatherResponse_<ContainerAllocator>& v)
  {
    s << indent << "city_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.city_name);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
    s << indent << "humidity: ";
    Printer<float>::stream(s, indent + "  ", v.humidity);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEATHER_INFO_MESSAGE_WEATHERRESPONSE_H
