; Auto-generated. Do not edit!


(cl:in-package project7-msg)


;//! \htmlinclude FollowPathResult.msg.html

(cl:defclass <FollowPathResult> (roslisp-msg-protocol:ros-message)
  ((total_elapsed_time
    :reader total_elapsed_time
    :initarg :total_elapsed_time
    :type cl:float
    :initform 0.0))
)

(cl:defclass FollowPathResult (<FollowPathResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowPathResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowPathResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name project7-msg:<FollowPathResult> is deprecated: use project7-msg:FollowPathResult instead.")))

(cl:ensure-generic-function 'total_elapsed_time-val :lambda-list '(m))
(cl:defmethod total_elapsed_time-val ((m <FollowPathResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project7-msg:total_elapsed_time-val is deprecated.  Use project7-msg:total_elapsed_time instead.")
  (total_elapsed_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowPathResult>) ostream)
  "Serializes a message object of type '<FollowPathResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'total_elapsed_time))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowPathResult>) istream)
  "Deserializes a message object of type '<FollowPathResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'total_elapsed_time) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowPathResult>)))
  "Returns string type for a message object of type '<FollowPathResult>"
  "project7/FollowPathResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowPathResult)))
  "Returns string type for a message object of type 'FollowPathResult"
  "project7/FollowPathResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowPathResult>)))
  "Returns md5sum for a message object of type '<FollowPathResult>"
  "fdb763de4a769f0ddee5d990c7476141")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowPathResult)))
  "Returns md5sum for a message object of type 'FollowPathResult"
  "fdb763de4a769f0ddee5d990c7476141")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowPathResult>)))
  "Returns full string definition for message of type '<FollowPathResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%float32 total_elapsed_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowPathResult)))
  "Returns full string definition for message of type 'FollowPathResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%float32 total_elapsed_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowPathResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowPathResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowPathResult
    (cl:cons ':total_elapsed_time (total_elapsed_time msg))
))
