; Auto-generated. Do not edit!


(cl:in-package project7-msg)


;//! \htmlinclude FollowPathFeedback.msg.html

(cl:defclass <FollowPathFeedback> (roslisp-msg-protocol:ros-message)
  ((total_distance_to_path
    :reader total_distance_to_path
    :initarg :total_distance_to_path
    :type cl:float
    :initform 0.0))
)

(cl:defclass FollowPathFeedback (<FollowPathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowPathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowPathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name project7-msg:<FollowPathFeedback> is deprecated: use project7-msg:FollowPathFeedback instead.")))

(cl:ensure-generic-function 'total_distance_to_path-val :lambda-list '(m))
(cl:defmethod total_distance_to_path-val ((m <FollowPathFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project7-msg:total_distance_to_path-val is deprecated.  Use project7-msg:total_distance_to_path instead.")
  (total_distance_to_path m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowPathFeedback>) ostream)
  "Serializes a message object of type '<FollowPathFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'total_distance_to_path))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowPathFeedback>) istream)
  "Deserializes a message object of type '<FollowPathFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'total_distance_to_path) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowPathFeedback>)))
  "Returns string type for a message object of type '<FollowPathFeedback>"
  "project7/FollowPathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowPathFeedback)))
  "Returns string type for a message object of type 'FollowPathFeedback"
  "project7/FollowPathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowPathFeedback>)))
  "Returns md5sum for a message object of type '<FollowPathFeedback>"
  "b37f6cb87e68ecced22623b0253fda11")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowPathFeedback)))
  "Returns md5sum for a message object of type 'FollowPathFeedback"
  "b37f6cb87e68ecced22623b0253fda11")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowPathFeedback>)))
  "Returns full string definition for message of type '<FollowPathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float32 total_distance_to_path~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowPathFeedback)))
  "Returns full string definition for message of type 'FollowPathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float32 total_distance_to_path~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowPathFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowPathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowPathFeedback
    (cl:cons ':total_distance_to_path (total_distance_to_path msg))
))
