; Auto-generated. Do not edit!


(cl:in-package project7-msg)


;//! \htmlinclude FollowPathGoal.msg.html

(cl:defclass <FollowPathGoal> (roslisp-msg-protocol:ros-message)
  ((path
    :reader path
    :initarg :path
    :type (cl:vector geometry_msgs-msg:Point)
   :initform (cl:make-array 0 :element-type 'geometry_msgs-msg:Point :initial-element (cl:make-instance 'geometry_msgs-msg:Point))))
)

(cl:defclass FollowPathGoal (<FollowPathGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowPathGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowPathGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name project7-msg:<FollowPathGoal> is deprecated: use project7-msg:FollowPathGoal instead.")))

(cl:ensure-generic-function 'path-val :lambda-list '(m))
(cl:defmethod path-val ((m <FollowPathGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project7-msg:path-val is deprecated.  Use project7-msg:path instead.")
  (path m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowPathGoal>) ostream)
  "Serializes a message object of type '<FollowPathGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'path))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'path))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowPathGoal>) istream)
  "Deserializes a message object of type '<FollowPathGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'path) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'path)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'geometry_msgs-msg:Point))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowPathGoal>)))
  "Returns string type for a message object of type '<FollowPathGoal>"
  "project7/FollowPathGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowPathGoal)))
  "Returns string type for a message object of type 'FollowPathGoal"
  "project7/FollowPathGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowPathGoal>)))
  "Returns md5sum for a message object of type '<FollowPathGoal>"
  "b58b29f4d3d5430fc9d5efc2f5262786")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowPathGoal)))
  "Returns md5sum for a message object of type 'FollowPathGoal"
  "b58b29f4d3d5430fc9d5efc2f5262786")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowPathGoal>)))
  "Returns full string definition for message of type '<FollowPathGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# FollowPath.action~%# Goal~%geometry_msgs/Point[] path~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowPathGoal)))
  "Returns full string definition for message of type 'FollowPathGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# FollowPath.action~%# Goal~%geometry_msgs/Point[] path~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowPathGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'path) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowPathGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowPathGoal
    (cl:cons ':path (path msg))
))
