; Auto-generated. Do not edit!


(cl:in-package project7-msg)


;//! \htmlinclude Navigate2DResult.msg.html

(cl:defclass <Navigate2DResult> (roslisp-msg-protocol:ros-message)
  ((elapsed_time
    :reader elapsed_time
    :initarg :elapsed_time
    :type cl:float
    :initform 0.0))
)

(cl:defclass Navigate2DResult (<Navigate2DResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Navigate2DResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Navigate2DResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name project7-msg:<Navigate2DResult> is deprecated: use project7-msg:Navigate2DResult instead.")))

(cl:ensure-generic-function 'elapsed_time-val :lambda-list '(m))
(cl:defmethod elapsed_time-val ((m <Navigate2DResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project7-msg:elapsed_time-val is deprecated.  Use project7-msg:elapsed_time instead.")
  (elapsed_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Navigate2DResult>) ostream)
  "Serializes a message object of type '<Navigate2DResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'elapsed_time))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Navigate2DResult>) istream)
  "Deserializes a message object of type '<Navigate2DResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'elapsed_time) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Navigate2DResult>)))
  "Returns string type for a message object of type '<Navigate2DResult>"
  "project7/Navigate2DResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Navigate2DResult)))
  "Returns string type for a message object of type 'Navigate2DResult"
  "project7/Navigate2DResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Navigate2DResult>)))
  "Returns md5sum for a message object of type '<Navigate2DResult>"
  "bc43e16eec5aeba078e3c28e74b0e8c1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Navigate2DResult)))
  "Returns md5sum for a message object of type 'Navigate2DResult"
  "bc43e16eec5aeba078e3c28e74b0e8c1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Navigate2DResult>)))
  "Returns full string definition for message of type '<Navigate2DResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%float32 elapsed_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Navigate2DResult)))
  "Returns full string definition for message of type 'Navigate2DResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%float32 elapsed_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Navigate2DResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Navigate2DResult>))
  "Converts a ROS message object to a list"
  (cl:list 'Navigate2DResult
    (cl:cons ':elapsed_time (elapsed_time msg))
))
